use std::fs::{self, File};
use std::io::Write;
use std::path::Path;

use domain::{Activity, TrackFeedback};
use std::collections::BTreeMap;
use std::collections::BTreeSet;
use zip::write::SimpleFileOptions;
use zip::{CompressionMethod, ZipWriter};

use crate::import::{
    hash_bytes, read_manifest_bounded, stage_pack, verify_generated_local_pack,
    verify_installed_pack, ImportLimits, InstalledPackFiles, PackImportError,
};
use crate::manifest::*;

fn asset_bytes() -> Vec<u8> {
    (0usize..4_096)
        .map(|index| (index.wrapping_mul(73) % 251) as u8)
        .collect()
}

fn fixture_manifest(bytes: &[u8]) -> ContentPackManifest {
    ContentPackManifest {
        format: FORMAT_NAME.to_owned(),
        format_version: FORMAT_VERSION,
        pack: PackMetadata {
            id: "test.focus-pack".to_owned(),
            title: "Test Focus Pack".to_owned(),
            description: "Generated metadata fixture; not music.".to_owned(),
            version: "1.0.0".to_owned(),
            app_version_requirement: ">=0.1.0, <2.0.0".to_owned(),
        },
        taxonomy: Taxonomy {
            genres: vec![TaxonomyTerm {
                id: "test-atmospheric".to_owned(),
                label: "Test Atmospheric".to_owned(),
            }],
            moods: vec![TaxonomyTerm {
                id: "test-calm".to_owned(),
                label: "Test Calm".to_owned(),
            }],
        },
        items: vec![ContentItem {
            id: "test-item".to_owned(),
            title: "Generated byte fixture".to_owned(),
            genre_ids: vec!["test-atmospheric".to_owned()],
            mood_ids: vec!["test-calm".to_owned()],
            activity_suitability: [
                (Activity::DeepWork, 0.8),
                (Activity::Motivation, 0.6),
                (Activity::Creativity, 0.7),
                (Activity::Learning, 0.8),
                (Activity::LightWork, 0.5),
            ]
            .into_iter()
            .map(|(activity, suitability)| ActivitySuitability {
                activity,
                suitability,
            })
            .collect(),
            provenance: Provenance {
                source: "Generated test bytes".to_owned(),
                licence_id: "CC0-1.0".to_owned(),
                licence_url: Some("https://creativecommons.org/publicdomain/zero/1.0/".to_owned()),
                composer: Some("Automated test fixture".to_owned()),
                generator: None,
                contains_lyrics: false,
                contains_speech: false,
            },
            analysis: TechnicalAnalysis {
                duration_seconds: 10.0,
                integrated_lufs: -20.0,
                true_peak_dbfs: -3.0,
                loudness_range_lu: 3.0,
                spectral_centroid_hz: 1_500.0,
                high_frequency_energy_ratio: 0.1,
                onset_density_per_second: 1.0,
                tempo_bpm: 90.0,
                tempo_confidence: 0.9,
                tempo_drift_percent: 0.2,
                section_change_novelty: 0.1,
                unexplained_silence_seconds: 0.0,
                clipped_samples: 0,
                discontinuity_detected: false,
                codec_errors_detected: false,
                corruption_detected: false,
                vocal_speech_likelihood: 0.01,
            },
            variants: vec![ContentVariant {
                id: "source".to_owned(),
                asset: AudioAsset {
                    path: "assets/test-item.wav".to_owned(),
                    sha256: hash_bytes(bytes),
                    bytes: bytes.len() as u64,
                    codec: AssetCodec::Wav,
                    sample_rate_hz: 44_100,
                    channels: 2,
                    bit_depth: Some(16),
                },
                safe_regions: vec![SafeRegion {
                    kind: SafeRegionKind::Loop,
                    start_seconds: 1.0,
                    end_seconds: 9.0,
                }],
                stimulation_available: vec![
                    StimulationAvailability::Off,
                    StimulationAvailability::Low,
                    StimulationAvailability::Medium,
                    StimulationAvailability::High,
                ],
            }],
            human_qa: HumanQa {
                status: HumanQaStatus::Approved,
                reviews: vec![
                    HumanReview {
                        reviewer_id: "reviewer-one".to_owned(),
                        reviewed_at: "2026-07-10T00:00:00Z".to_owned(),
                        notes: "Generated fixture metadata review.".to_owned(),
                        representative_work_session: true,
                    },
                    HumanReview {
                        reviewer_id: "reviewer-two".to_owned(),
                        reviewed_at: "2026-07-10T00:00:00Z".to_owned(),
                        notes: "Second generated fixture metadata review.".to_owned(),
                        representative_work_session: false,
                    },
                ],
            },
        }],
    }
}

#[test]
fn direct_item_selection_keeps_the_requested_item_and_ignores_focus_ranking() {
    let manifest = fixture_manifest(&asset_bytes());
    let selection = crate::select_playback_plan_for_item_with_eligibility(
        &[manifest],
        Activity::DeepWork,
        "test-item",
        &crate::PlaybackEligibility::published_only(),
    )
    .expect("fixture item is continuously playable");
    assert_eq!(selection.primary().item_id, "test-item");
}

fn assert_invalid(mutator: impl FnOnce(&mut ContentPackManifest)) {
    let bytes = asset_bytes();
    let mut manifest = fixture_manifest(&bytes);
    mutator(&mut manifest);
    assert!(manifest.validate_published().is_err());
}

#[test]
fn manifest_round_trip_and_canonicalization_are_stable() {
    let bytes = asset_bytes();
    let mut manifest = fixture_manifest(&bytes);
    manifest.items[0].variants[0]
        .stimulation_available
        .reverse();
    let canonical = canonical_manifest_bytes(&manifest).unwrap();
    let decoded: ContentPackManifest = serde_json::from_slice(&canonical).unwrap();
    assert_eq!(decoded, manifest.canonicalized());
    assert_eq!(canonical_manifest_bytes(&decoded).unwrap(), canonical);
}

#[test]
fn generated_local_verification_uses_its_own_trust_contract() {
    let temp = tempfile::tempdir().unwrap();
    let job_id = "job-local-catalogue";
    let asset = b"local generated flac fixture";
    let mut manifest = fixture_manifest(asset);
    manifest.pack.id = format!("generated.local.{job_id}");
    manifest.pack.version = "1.0.0".to_owned();
    manifest.pack.app_version_requirement = "*".to_owned();
    manifest.items[0].id = format!("generated.local.{job_id}.item");
    manifest.items[0].human_qa = HumanQa {
        status: HumanQaStatus::Draft,
        reviews: vec![],
    };
    manifest.items[0].variants[0].asset = AudioAsset {
        path: format!("assets/generated/{job_id}.flac"),
        sha256: hash_bytes(asset),
        bytes: asset.len() as u64,
        codec: AssetCodec::Flac,
        sample_rate_hz: 48_000,
        channels: 2,
        bit_depth: Some(24),
    };
    manifest.validate_generated_local(job_id).unwrap();
    assert!(manifest.validate_published().is_err());

    let directory = temp.path().join("generated");
    fs::create_dir_all(directory.join("assets/generated")).unwrap();
    let canonical = canonical_manifest_bytes(&manifest).unwrap();
    fs::write(directory.join(MANIFEST_PATH), &canonical).unwrap();
    fs::write(
        directory.join(format!("assets/generated/{job_id}.flac")),
        asset,
    )
    .unwrap();

    assert!(verify_generated_local_pack(&directory, &hash_bytes(&canonical)).is_ok());
    assert!(verify_installed_pack(&directory, &hash_bytes(&canonical)).is_err());
}

#[test]
fn app_semver_compatibility_is_enforced_separately_from_publication() {
    let manifest = fixture_manifest(&asset_bytes());
    assert!(manifest.validate_app_compatibility("0.1.0").is_ok());
    assert!(manifest.validate_app_compatibility("0.2.0-beta.1").is_ok());
    assert!(manifest.validate_app_compatibility("2.0.0").is_err());
    assert!(manifest.validate_app_compatibility("not-semver").is_err());

    let mut capped = manifest;
    capped.pack.app_version_requirement = ">=0.1.0, <0.2.0".to_owned();
    assert!(capped.validate_app_compatibility("0.2.0-beta.1").is_err());
}

#[test]
fn published_ogg_opus_requires_its_exact_playback_contract() {
    let bytes = asset_bytes();
    let mut manifest = fixture_manifest(&bytes);
    manifest.format_version = FORMAT_VERSION_2;
    let asset = &mut manifest.items[0].variants[0].asset;
    asset.path = "assets/test-item.opus".to_owned();
    asset.codec = AssetCodec::OggOpus;
    asset.sample_rate_hz = 48_000;
    asset.channels = 2;
    asset.bit_depth = None;
    manifest.validate_published().unwrap();

    let mut v1_opus = manifest.clone();
    v1_opus.format_version = FORMAT_VERSION;
    assert!(v1_opus.validate_published().is_err());

    let mut v2_flac = fixture_manifest(&bytes);
    v2_flac.format_version = FORMAT_VERSION_2;
    assert!(v2_flac.validate_published().is_err());

    let mutations: [fn(&mut AudioAsset); 3] = [
        |asset: &mut AudioAsset| asset.sample_rate_hz = 44_100,
        |asset: &mut AudioAsset| asset.channels = 3,
        |asset: &mut AudioAsset| asset.bit_depth = Some(16),
    ];
    for mutate in mutations {
        let mut invalid = manifest.clone();
        mutate(&mut invalid.items[0].variants[0].asset);
        assert!(invalid.validate_published().is_err());
    }
}

#[test]
fn required_published_metadata_and_safety_gates_fail_closed() {
    assert_invalid(|m| m.pack.version = "not-semver".to_owned());
    assert_invalid(|m| m.pack.app_version_requirement = "nope".to_owned());
    assert_invalid(|m| m.taxonomy.genres.clear());
    assert_invalid(|m| m.items.push(m.items[0].clone()));
    assert_invalid(|m| m.items[0].genre_ids = vec!["unknown".to_owned()]);
    assert_invalid(|m| m.items[0].mood_ids.clear());
    assert_invalid(|m| m.items[0].activity_suitability.clear());
    assert_invalid(|m| m.items[0].provenance.source.clear());
    assert_invalid(|m| m.items[0].provenance.licence_id.clear());
    assert_invalid(|m| m.items[0].provenance.composer = None);
    assert_invalid(|m| m.items[0].provenance.contains_lyrics = true);
    assert_invalid(|m| m.items[0].provenance.contains_speech = true);
    assert_invalid(|m| m.items[0].analysis.vocal_speech_likelihood = 0.06);
    assert_invalid(|m| m.items[0].analysis.clipped_samples = 1);
    assert_invalid(|m| m.items[0].analysis.corruption_detected = true);
    assert_invalid(|m| m.items[0].analysis.codec_errors_detected = true);
    assert_invalid(|m| m.items[0].variants[0].asset.sha256 = "A".repeat(64));
    assert_invalid(|m| m.items[0].analysis.discontinuity_detected = true);
    assert_invalid(|m| m.items[0].analysis.unexplained_silence_seconds = 0.1);
    assert_invalid(|m| {
        let asset = &mut m.items[0].variants[0].asset;
        asset.codec = AssetCodec::OggOpus;
        asset.path = "assets/test-item.opus".to_owned();
    });
    assert_invalid(|m| m.items[0].analysis.integrated_lufs = f32::NAN);
    assert_invalid(|m| m.items[0].variants[0].asset.sha256 = "bad".to_owned());
    assert_invalid(|m| m.items[0].variants[0].asset.path = "../escape.wav".to_owned());
    for unsafe_path in [
        "assets/NUL.wav",
        "assets/con.txt",
        "assets/trailing.wav.",
        "assets/trailing .wav",
        "assets/café.wav",
        "assets/.hidden.wav",
    ] {
        assert_invalid(|m| m.items[0].variants[0].asset.path = unsafe_path.to_owned());
    }
    assert_invalid(|m| {
        let mut variant = m.items[0].variants[0].clone();
        variant.id = "case-alias".to_owned();
        variant.asset.path = "assets/TEST-ITEM.wav".to_owned();
        m.items[0].variants.push(variant);
    });
    assert_invalid(|m| m.items[0].variants[0].safe_regions.clear());
    assert_invalid(|m| m.items[0].variants[0].safe_regions[0].end_seconds = 11.0);
    assert_invalid(|m| m.items[0].variants[0].stimulation_available.clear());
    assert_invalid(|m| m.items[0].human_qa.status = HumanQaStatus::Draft);
    assert_invalid(|m| m.items[0].human_qa.reviews.clear());
    assert_invalid(|m| {
        for review in &mut m.items[0].human_qa.reviews {
            review.representative_work_session = false;
        }
    });
}

#[test]
fn owner_waived_validation_is_explicit_and_does_not_change_published_qa() {
    let bytes = asset_bytes();
    let mut manifest = fixture_manifest(&bytes);
    manifest.items[0].human_qa.status = HumanQaStatus::Draft;
    manifest.items[0].human_qa.reviews.clear();
    assert!(manifest.validate_bundled_owner_waived().is_ok());
    assert!(manifest.validate_published().is_err());
}

#[test]
fn pending_qa_needs_explicit_build_eligibility_for_selection() {
    let bytes = asset_bytes();
    let mut manifest = fixture_manifest(&bytes);
    manifest.items[0].human_qa.status = HumanQaStatus::Draft;
    manifest.items[0].human_qa.reviews.clear();
    let feedback = BTreeMap::new();
    let input = crate::PlaybackSelectionInput {
        activity: Activity::DeepWork,
        genre_id: None,
        mood_id: None,
        previous_item_id: None,
        item_feedback: &feedback,
    };
    assert!(crate::select_playback_plan(&[manifest.clone()], input).is_none());
    assert!(crate::select_playback_plan_with_eligibility(
        &[manifest.clone()],
        input,
        &crate::PlaybackEligibility::with_owner_waived_bundled_item("test-item".to_owned()),
    )
    .is_some());
    assert!(crate::select_playback_plan_with_eligibility(
        &[manifest],
        input,
        &crate::PlaybackEligibility::published_only()
            .allowing_app_generated_items(["test-item".to_owned()]),
    )
    .is_some());
}

#[test]
fn legacy_app_generated_item_gets_a_bounded_full_track_loop() {
    let bytes = asset_bytes();
    let mut manifest = fixture_manifest(&bytes);
    manifest.items[0].human_qa.status = HumanQaStatus::Draft;
    manifest.items[0].human_qa.reviews.clear();
    manifest.items[0].variants[0].safe_regions.clear();
    manifest.items[0].variants[0].stimulation_available = vec![StimulationAvailability::Off];
    manifest.items[0].analysis.discontinuity_detected = false;
    let feedback = BTreeMap::new();
    let input = crate::PlaybackSelectionInput {
        activity: Activity::DeepWork,
        genre_id: None,
        mood_id: None,
        previous_item_id: None,
        item_feedback: &feedback,
    };

    let selection = crate::select_playback_plan_with_eligibility(
        &[manifest],
        input,
        &crate::PlaybackEligibility::published_only()
            .allowing_app_generated_items(["test-item".to_owned()]),
    )
    .expect("validated app-generated tracks remain playable after the loop contract upgrade");
    assert_eq!(selection.tracks.len(), 1);
    assert_eq!(selection.primary().safe_regions.len(), 1);
    assert_eq!(selection.primary().safe_regions[0].start_seconds, 0.0);
    assert_eq!(selection.primary().safe_regions[0].end_seconds, 10.0);
}

#[test]
fn playback_selection_is_stable_and_avoids_an_immediate_item_repeat() {
    let bytes = asset_bytes();
    let mut first = fixture_manifest(&bytes);
    first.pack.id = "pack-a".to_owned();
    first.items[0].id = "item-a".to_owned();
    first.items[0].variants[0].asset.path = "assets/item-a.wav".to_owned();
    let mut second = fixture_manifest(&bytes);
    second.pack.id = "pack-b".to_owned();
    second.items[0].id = "item-b".to_owned();
    second.items[0].variants[0].asset.path = "assets/item-b.wav".to_owned();

    let stable = crate::select_playback_plan(
        &[second.clone(), first.clone()],
        crate::PlaybackSelectionInput {
            activity: Activity::DeepWork,
            genre_id: None,
            mood_id: None,
            previous_item_id: None,
            item_feedback: &Default::default(),
        },
    )
    .unwrap();
    assert_eq!(stable.primary().item_id, "item-a");

    let rotated = crate::select_playback_plan(
        &[first, second],
        crate::PlaybackSelectionInput {
            activity: Activity::DeepWork,
            genre_id: None,
            mood_id: None,
            previous_item_id: Some("item-a"),
            item_feedback: &Default::default(),
        },
    )
    .unwrap();
    assert_eq!(rotated.primary().item_id, "item-b");
}

#[test]
fn feedback_prioritizes_helpful_excludes_distracting_and_preserves_activity_and_genre_filters() {
    let bytes = asset_bytes();
    let mut helpful = fixture_manifest(&bytes);
    helpful.pack.id = "helpful-pack".to_owned();
    helpful.items[0].id = "helpful-item".to_owned();
    helpful.items[0].variants[0].asset.path = "assets/helpful.wav".to_owned();
    helpful.items[0]
        .activity_suitability
        .iter_mut()
        .find(|entry| entry.activity == Activity::LightWork)
        .unwrap()
        .suitability = 0.0;
    let mut neutral = helpful.clone();
    neutral.pack.id = "neutral-pack".to_owned();
    neutral.items[0].id = "neutral-item".to_owned();
    neutral.items[0].variants[0].asset.path = "assets/neutral.wav".to_owned();
    neutral.items[0]
        .activity_suitability
        .iter_mut()
        .find(|entry| entry.activity == Activity::DeepWork)
        .unwrap()
        .suitability = 0.99;
    let mut feedback = BTreeMap::new();
    feedback.insert("helpful-item".to_owned(), TrackFeedback::HelpsFocus);
    feedback.insert("neutral-item".to_owned(), TrackFeedback::Distracting);
    let input = crate::PlaybackSelectionInput {
        activity: Activity::DeepWork,
        genre_id: Some("test-atmospheric"),
        mood_id: None,
        previous_item_id: None,
        item_feedback: &feedback,
    };
    assert_eq!(
        crate::select_playback_plan(&[helpful.clone(), neutral.clone()], input)
            .unwrap()
            .primary()
            .item_id,
        "helpful-item"
    );
    feedback.insert("helpful-item".to_owned(), TrackFeedback::Distracting);
    assert!(crate::select_playback_plan(
        &[helpful.clone(), neutral],
        crate::PlaybackSelectionInput {
            activity: Activity::DeepWork,
            genre_id: Some("test-atmospheric"),
            mood_id: None,
            previous_item_id: None,
            item_feedback: &feedback
        }
    )
    .is_none());
    let empty = BTreeMap::new();
    assert!(crate::select_playback_plan(
        &[helpful],
        crate::PlaybackSelectionInput {
            activity: Activity::LightWork,
            genre_id: Some("test-atmospheric"),
            mood_id: None,
            previous_item_id: None,
            item_feedback: &empty
        }
    )
    .is_none());
}

#[test]
fn playback_selection_requires_all_intensities_for_gapless_live_changes() {
    let bytes = asset_bytes();
    let mut manifest = fixture_manifest(&bytes);
    manifest.items[0].variants[0]
        .stimulation_available
        .retain(|level| *level != StimulationAvailability::High);
    assert!(crate::select_playback_plan(
        &[manifest],
        crate::PlaybackSelectionInput {
            activity: Activity::DeepWork,
            genre_id: None,
            mood_id: None,
            previous_item_id: None,
            item_feedback: &Default::default(),
        }
    )
    .is_none());
}

#[test]
fn crossfade_selection_requires_two_sided_nonzero_authored_regions() {
    let bytes = asset_bytes();
    let mut first = fixture_manifest(&bytes);
    first.pack.id = "pack-a".to_owned();
    first.items[0].id = "item-a".to_owned();
    first.items[0].variants[0].asset.path = "assets/item-a.wav".to_owned();
    first.items[0].variants[0].safe_regions = vec![
        SafeRegion {
            kind: SafeRegionKind::Crossfade,
            start_seconds: 1.0,
            end_seconds: 2.5,
        },
        SafeRegion {
            kind: SafeRegionKind::Crossfade,
            start_seconds: 7.0,
            end_seconds: 9.0,
        },
    ];
    let mut second = first.clone();
    second.pack.id = "pack-b".to_owned();
    second.items[0].id = "item-b".to_owned();
    second.items[0].variants[0].asset.path = "assets/item-b.wav".to_owned();
    second.items[0].variants[0].safe_regions[0].end_seconds = 2.0;
    second.items[0].variants[0].safe_regions[1].start_seconds = 8.0;

    let selected = crate::select_playback_plan(
        &[first.clone(), second.clone()],
        crate::PlaybackSelectionInput {
            activity: Activity::DeepWork,
            genre_id: None,
            mood_id: None,
            previous_item_id: None,
            item_feedback: &Default::default(),
        },
    )
    .unwrap();
    assert_eq!(selected.tracks.len(), 2);

    first.items[0].variants[0].safe_regions.truncate(1);
    second.items[0].variants[0].safe_regions.truncate(1);
    assert!(crate::select_playback_plan(
        &[first, second],
        crate::PlaybackSelectionInput {
            activity: Activity::DeepWork,
            genre_id: None,
            mood_id: None,
            previous_item_id: None,
            item_feedback: &Default::default(),
        }
    )
    .is_none());
}

#[test]
fn genre_filter_requires_exact_item_genre_and_no_match_is_none() {
    let bytes = asset_bytes();
    let mut ambient = fixture_manifest(&bytes);
    ambient.pack.id = "ambient-pack".to_owned();
    ambient.items[0].id = "ambient-item".to_owned();
    let mut rhythmic = fixture_manifest(&bytes);
    rhythmic.pack.id = "rhythmic-pack".to_owned();
    rhythmic.items[0].id = "rhythmic-item".to_owned();
    rhythmic.items[0].genre_ids = vec!["test-rhythmic".to_owned()];
    rhythmic.taxonomy.genres[0].id = "test-rhythmic".to_owned();
    rhythmic.taxonomy.genres[0].label = "Rhythmic".to_owned();
    let selection = crate::select_playback_plan(
        &[ambient.clone(), rhythmic.clone()],
        crate::PlaybackSelectionInput {
            activity: Activity::DeepWork,
            genre_id: Some("test-rhythmic"),
            mood_id: None,
            previous_item_id: None,
            item_feedback: &Default::default(),
        },
    )
    .unwrap();
    assert!(selection
        .tracks
        .iter()
        .all(|track| track.genre_ids == ["test-rhythmic"]));
    assert!(crate::select_playback_plan(
        &[ambient, rhythmic],
        crate::PlaybackSelectionInput {
            activity: Activity::DeepWork,
            genre_id: Some("missing"),
            mood_id: None,
            previous_item_id: None,
            item_feedback: &Default::default(),
        },
    )
    .is_none());
}

#[test]
fn available_genres_are_playable_and_deterministically_ordered() {
    let bytes = asset_bytes();
    let mut first = fixture_manifest(&bytes);
    first.pack.id = "z-pack".to_owned();
    first.items[0].genre_ids = vec!["zeta".to_owned()];
    first.taxonomy.genres[0].id = "zeta".to_owned();
    first.taxonomy.genres[0].label = "Zeta".to_owned();
    let mut second = fixture_manifest(&bytes);
    second.pack.id = "a-pack".to_owned();
    second.items[0].genre_ids = vec!["alpha".to_owned()];
    second.taxonomy.genres[0].id = "alpha".to_owned();
    second.taxonomy.genres[0].label = "Alpha".to_owned();
    assert_eq!(
        crate::available_genres(&[first, second], Activity::DeepWork)
            .into_iter()
            .map(|genre| genre.id)
            .collect::<Vec<_>>(),
        ["alpha", "zeta"]
    );
}

#[test]
fn mood_filter_intersects_activity_and_genre_and_options_are_playable() {
    let bytes = asset_bytes();
    let mut first = fixture_manifest(&bytes);
    first.pack.id = "z-pack".to_owned();
    first.items[0].mood_ids = vec!["zeta".to_owned()];
    first.taxonomy.moods[0].id = "zeta".to_owned();
    first.taxonomy.moods[0].label = "Zeta".to_owned();
    let mut second = fixture_manifest(&bytes);
    second.pack.id = "a-pack".to_owned();
    second.items[0].mood_ids = vec!["alpha".to_owned()];
    second.taxonomy.moods[0].id = "alpha".to_owned();
    second.taxonomy.moods[0].label = "Alpha".to_owned();
    let moods = crate::available_moods(
        &[first.clone(), second.clone()],
        Activity::DeepWork,
        Some("test-atmospheric"),
    );
    assert_eq!(
        moods.into_iter().map(|mood| mood.id).collect::<Vec<_>>(),
        ["alpha", "zeta"]
    );
    let selection = crate::select_playback_plan(
        &[first, second],
        crate::PlaybackSelectionInput {
            activity: Activity::DeepWork,
            genre_id: Some("test-atmospheric"),
            mood_id: Some("alpha"),
            previous_item_id: None,
            item_feedback: &Default::default(),
        },
    )
    .unwrap();
    assert!(selection
        .tracks
        .iter()
        .all(|track| track.mood_ids == ["alpha"]));
}

#[test]
fn actual_manifest_reads_are_hard_bounded_and_size_checked() {
    let mut over_limit = std::io::Cursor::new(vec![b'x'; 17]);
    assert!(matches!(
        read_manifest_bounded(&mut over_limit, 8, 16),
        Err(PackImportError::ManifestTooLarge)
    ));

    let mut short = std::io::Cursor::new(vec![b'x'; 7]);
    assert!(matches!(
        read_manifest_bounded(&mut short, 8, 16),
        Err(PackImportError::ManifestSizeMismatch)
    ));
}

#[test]
fn structurally_missing_analysis_is_rejected_by_deserialization() {
    let bytes = asset_bytes();
    let mut value = serde_json::to_value(fixture_manifest(&bytes)).unwrap();
    value["items"][0]
        .as_object_mut()
        .unwrap()
        .remove("analysis");
    assert!(serde_json::from_value::<ContentPackManifest>(value).is_err());
}

fn write_pack(
    path: &Path,
    manifest: &ContentPackManifest,
    actual_asset: &[u8],
    extras: &[(&str, &[u8])],
    asset_compression: CompressionMethod,
) {
    let file = File::create(path).unwrap();
    let mut writer = ZipWriter::new(file);
    let stored = SimpleFileOptions::default().compression_method(CompressionMethod::Stored);
    let compressed = SimpleFileOptions::default().compression_method(asset_compression);
    writer.start_file(MANIFEST_PATH, stored).unwrap();
    writer
        .write_all(&canonical_manifest_bytes(manifest).unwrap())
        .unwrap();
    writer
        .start_file(&manifest.items[0].variants[0].asset.path, compressed)
        .unwrap();
    writer.write_all(actual_asset).unwrap();
    for &(name, bytes) in extras {
        writer.start_file(name, stored).unwrap();
        writer.write_all(bytes).unwrap();
    }
    writer.finish().unwrap();
}

fn install_fixture(root: &Path, label: &str) -> InstalledPackFiles {
    let bytes = asset_bytes();
    let manifest = fixture_manifest(&bytes);
    let archive = root.join(format!("{label}.adhdpack"));
    write_pack(&archive, &manifest, &bytes, &[], CompressionMethod::Stored);
    stage_pack(
        &archive,
        &root.join(format!("stage-{label}")),
        ImportLimits::default(),
    )
    .unwrap()
    .install_to(&root.join(format!("installed-{label}")))
    .unwrap()
}

#[test]
fn secure_stage_and_atomic_install_succeed_for_generated_fixture() {
    let temp = tempfile::tempdir().unwrap();
    let bytes = asset_bytes();
    let manifest = fixture_manifest(&bytes);
    let archive = temp.path().join("fixture.adhdpack");
    write_pack(&archive, &manifest, &bytes, &[], CompressionMethod::Stored);

    let staged = stage_pack(
        &archive,
        &temp.path().join("staging"),
        ImportLimits::default(),
    )
    .unwrap();
    let target = temp.path().join("installed/test.focus-pack/1.0.0");
    let installed = staged.install_to(&target).unwrap();
    assert_eq!(installed.directory, target);
    assert!(target.join(MANIFEST_PATH).is_file());
    assert!(target.join("assets/test-item.wav").is_file());
}

#[test]
fn ordinary_archive_with_pending_qa_is_rejected() {
    let temp = tempfile::tempdir().unwrap();
    let bytes = asset_bytes();
    let mut manifest = fixture_manifest(&bytes);
    manifest.items[0].human_qa.status = HumanQaStatus::Draft;
    manifest.items[0].human_qa.reviews.clear();
    let archive = temp.path().join("pending.adhdpack");
    write_pack(&archive, &manifest, &bytes, &[], CompressionMethod::Stored);
    assert!(matches!(
        stage_pack(
            &archive,
            &temp.path().join("staging"),
            ImportLimits::default()
        ),
        Err(PackImportError::ManifestValidation(_))
    ));
}

#[test]
fn traversal_duplicate_and_undeclared_zip_payloads_are_rejected() {
    let temp = tempfile::tempdir().unwrap();
    let bytes = asset_bytes();
    let manifest = fixture_manifest(&bytes);

    let traversal = temp.path().join("traversal.adhdpack");
    write_pack(
        &traversal,
        &manifest,
        &bytes,
        &[("../escape.wav", b"x")],
        CompressionMethod::Stored,
    );
    assert!(matches!(
        stage_pack(&traversal, &temp.path().join("s1"), ImportLimits::default()),
        Err(PackImportError::UnsafePath(_))
    ));

    let undeclared = temp.path().join("undeclared.adhdpack");
    write_pack(
        &undeclared,
        &manifest,
        &bytes,
        &[("assets/extra.wav", b"x")],
        CompressionMethod::Stored,
    );
    assert!(matches!(
        stage_pack(
            &undeclared,
            &temp.path().join("s2"),
            ImportLimits::default()
        ),
        Err(PackImportError::UndeclaredPayload(_))
    ));

    let duplicate = temp.path().join("duplicate.adhdpack");
    write_pack(
        &duplicate,
        &manifest,
        &bytes,
        &[("assets/TEST-ITEM.wav", b"duplicate")],
        CompressionMethod::Stored,
    );
    assert!(matches!(
        stage_pack(&duplicate, &temp.path().join("s3"), ImportLimits::default()),
        Err(PackImportError::DuplicatePath(_))
    ));
}

#[test]
fn unsafe_cross_platform_zip_names_and_explicit_directories_are_rejected() {
    let unsafe_names = [
        "assets/NUL.wav",
        "assets/con.txt",
        "assets/trailing.wav.",
        "assets/trailing .wav",
        "assets/café.wav",
    ];
    for (index, name) in unsafe_names.into_iter().enumerate() {
        let temp = tempfile::tempdir().unwrap();
        let bytes = asset_bytes();
        let manifest = fixture_manifest(&bytes);
        let archive = temp.path().join(format!("unsafe-{index}.adhdpack"));
        write_pack(
            &archive,
            &manifest,
            &bytes,
            &[(name, b"extra")],
            CompressionMethod::Stored,
        );
        assert!(matches!(
            stage_pack(
                &archive,
                &temp.path().join("stage"),
                ImportLimits::default()
            ),
            Err(PackImportError::UnsafePath(_))
        ));
    }

    let temp = tempfile::tempdir().unwrap();
    let bytes = asset_bytes();
    let manifest = fixture_manifest(&bytes);
    let archive = temp.path().join("directory-alias.adhdpack");
    let file = File::create(&archive).unwrap();
    let mut writer = ZipWriter::new(file);
    let options = SimpleFileOptions::default().compression_method(CompressionMethod::Stored);
    writer.start_file(MANIFEST_PATH, options).unwrap();
    writer
        .write_all(&canonical_manifest_bytes(&manifest).unwrap())
        .unwrap();
    writer
        .add_directory("assets/test-item.wav/", options)
        .unwrap();
    writer.start_file("assets/test-item.wav", options).unwrap();
    writer.write_all(&bytes).unwrap();
    writer.finish().unwrap();
    assert!(matches!(
        stage_pack(
            &archive,
            &temp.path().join("stage"),
            ImportLimits::default()
        ),
        Err(PackImportError::UnsupportedEntry(_))
    ));
}

#[test]
fn installed_tree_rejects_unsafe_names_and_linked_assets_root() {
    let temp = tempfile::tempdir().unwrap();
    let bytes = asset_bytes();
    let manifest = fixture_manifest(&bytes);
    let archive = temp.path().join("fixture.adhdpack");
    write_pack(&archive, &manifest, &bytes, &[], CompressionMethod::Stored);
    let installed = stage_pack(
        &archive,
        &temp.path().join("staging"),
        ImportLimits::default(),
    )
    .unwrap()
    .install_to(&temp.path().join("installed"))
    .unwrap();
    fs::write(installed.directory.join("assets/café.wav"), b"unsafe").unwrap();
    assert!(matches!(
        verify_installed_pack(&installed.directory, &installed.manifest_sha256),
        Err(PackImportError::UnsafePath(_))
    ));

    fs::remove_file(installed.directory.join("assets/café.wav")).unwrap();
    let real_assets = temp.path().join("real-assets");
    fs::rename(installed.directory.join("assets"), &real_assets).unwrap();
    #[cfg(windows)]
    let linked =
        std::os::windows::fs::symlink_dir(&real_assets, installed.directory.join("assets"));
    #[cfg(unix)]
    let linked = std::os::unix::fs::symlink(&real_assets, installed.directory.join("assets"));
    #[cfg(not(any(windows, unix)))]
    let linked: Result<(), std::io::Error> = Err(std::io::Error::new(
        std::io::ErrorKind::Unsupported,
        "symlink test unsupported",
    ));
    if linked.is_ok() {
        assert!(matches!(
            verify_installed_pack(&installed.directory, &installed.manifest_sha256),
            Err(PackImportError::InstalledPackCorrupt(_))
        ));
    }
}

#[test]
fn installed_root_is_closed_world_and_rejects_root_links() {
    let temp = tempfile::tempdir().unwrap();

    let extra_file = install_fixture(temp.path(), "extra-file");
    fs::write(extra_file.directory.join("unexpected.bin"), b"unexpected").unwrap();
    assert!(matches!(
        verify_installed_pack(&extra_file.directory, &extra_file.manifest_sha256),
        Err(PackImportError::InstalledPackCorrupt(_))
    ));

    let extra_directory = install_fixture(temp.path(), "extra-directory");
    fs::create_dir(extra_directory.directory.join("unexpected-directory")).unwrap();
    assert!(matches!(
        verify_installed_pack(&extra_directory.directory, &extra_directory.manifest_sha256),
        Err(PackImportError::InstalledPackCorrupt(_))
    ));

    #[cfg(not(windows))]
    {
        let manifest_alias = install_fixture(temp.path(), "manifest-alias");
        fs::copy(
            manifest_alias.directory.join(MANIFEST_PATH),
            manifest_alias.directory.join("Manifest.json"),
        )
        .unwrap();
        assert!(matches!(
            verify_installed_pack(&manifest_alias.directory, &manifest_alias.manifest_sha256),
            Err(PackImportError::InstalledPackCorrupt(_))
        ));

        let assets_alias = install_fixture(temp.path(), "assets-alias");
        fs::create_dir(assets_alias.directory.join("Assets")).unwrap();
        assert!(matches!(
            verify_installed_pack(&assets_alias.directory, &assets_alias.manifest_sha256),
            Err(PackImportError::InstalledPackCorrupt(_))
        ));
    }

    let linked_root = install_fixture(temp.path(), "linked-root");
    let real_root = temp.path().join("real-installed-root");
    fs::rename(&linked_root.directory, &real_root).unwrap();
    #[cfg(windows)]
    let linked = std::os::windows::fs::symlink_dir(&real_root, &linked_root.directory);
    #[cfg(unix)]
    let linked = std::os::unix::fs::symlink(&real_root, &linked_root.directory);
    #[cfg(not(any(windows, unix)))]
    let linked: Result<(), std::io::Error> = Err(std::io::Error::new(
        std::io::ErrorKind::Unsupported,
        "symlink test unsupported",
    ));
    if linked.is_ok() {
        assert!(matches!(
            verify_installed_pack(&linked_root.directory, &linked_root.manifest_sha256),
            Err(PackImportError::InstalledPackCorrupt(_))
        ));
    }
}

#[test]
fn symbolic_link_entries_are_rejected() {
    let temp = tempfile::tempdir().unwrap();
    let bytes = asset_bytes();
    let manifest = fixture_manifest(&bytes);
    let archive_path = temp.path().join("symlink.adhdpack");
    let file = File::create(&archive_path).unwrap();
    let mut writer = ZipWriter::new(file);
    let options = SimpleFileOptions::default().compression_method(CompressionMethod::Stored);
    writer.start_file(MANIFEST_PATH, options).unwrap();
    writer
        .write_all(&canonical_manifest_bytes(&manifest).unwrap())
        .unwrap();
    writer.start_file("assets/test-item.wav", options).unwrap();
    writer.write_all(&bytes).unwrap();
    writer
        .add_symlink("assets/link.wav", "test-item.wav", options)
        .unwrap();
    writer.finish().unwrap();

    assert!(matches!(
        stage_pack(
            &archive_path,
            &temp.path().join("staging"),
            ImportLimits::default()
        ),
        Err(PackImportError::UnsupportedEntry(_))
    ));
}

#[test]
fn hash_mismatch_and_staging_cleanup_are_enforced() {
    let temp = tempfile::tempdir().unwrap();
    let bytes = asset_bytes();
    let manifest = fixture_manifest(&bytes);
    let archive = temp.path().join("bad-hash.adhdpack");
    let mut bad = bytes.clone();
    bad[10] ^= 0xff;
    write_pack(&archive, &manifest, &bad, &[], CompressionMethod::Stored);
    let staging = temp.path().join("staging");

    assert!(matches!(
        stage_pack(&archive, &staging, ImportLimits::default()),
        Err(PackImportError::HashMismatch(_))
    ));
    assert_eq!(fs::read_dir(staging).unwrap().count(), 0);
}

#[test]
fn bombish_ratio_and_entry_limits_are_rejected_before_extraction() {
    let temp = tempfile::tempdir().unwrap();
    let bytes = vec![0u8; 64 * 1024];
    let manifest = fixture_manifest(&bytes);
    let archive = temp.path().join("compressed.adhdpack");
    write_pack(
        &archive,
        &manifest,
        &bytes,
        &[],
        CompressionMethod::Deflated,
    );
    let limits = ImportLimits {
        max_compression_ratio: 5.0,
        ..ImportLimits::default()
    };
    assert!(matches!(
        stage_pack(&archive, &temp.path().join("s1"), limits),
        Err(PackImportError::CompressionRatio(_))
    ));

    let limits = ImportLimits {
        max_entry_bytes: 100,
        ..ImportLimits::default()
    };
    assert!(matches!(
        stage_pack(&archive, &temp.path().join("s2"), limits),
        Err(PackImportError::EntryTooLarge(_))
    ));
}

fn single_loop_manifest(
    bytes: &[u8],
    pack_id: &str,
    item_id: &str,
    duration_seconds: f32,
    deep_work_suitability: f32,
) -> ContentPackManifest {
    let mut manifest = fixture_manifest(bytes);
    manifest.pack.id = pack_id.to_owned();
    manifest.pack.title = format!("{pack_id} title");
    manifest.items[0].id = item_id.to_owned();
    manifest.items[0].title = item_id.to_owned();
    manifest.items[0].variants[0].asset.path = format!("assets/{item_id}.wav");
    manifest.items[0].analysis.duration_seconds = duration_seconds;
    manifest.items[0]
        .activity_suitability
        .iter_mut()
        .find(|entry| entry.activity == Activity::DeepWork)
        .unwrap()
        .suitability = deep_work_suitability;
    manifest
}

fn estimated_samples(candidate: &crate::PlaybackCandidate) -> f64 {
    f64::from(candidate.duration_seconds)
        * f64::from(candidate.asset.sample_rate_hz)
        * f64::from(candidate.asset.channels)
}

#[test]
fn loop_queue_is_bounded_to_eight_distinct_tracks_with_primary_first() {
    let bytes = asset_bytes();
    let manifests: Vec<_> = (0..10)
        .map(|index| {
            single_loop_manifest(
                &bytes,
                &format!("pack-{index}"),
                &format!("item-{index}"),
                10.0,
                0.8,
            )
        })
        .collect();
    let selection = crate::select_playback_plan(
        &manifests,
        crate::PlaybackSelectionInput {
            activity: Activity::DeepWork,
            genre_id: None,
            mood_id: None,
            previous_item_id: None,
            item_feedback: &Default::default(),
        },
    )
    .unwrap();
    assert_eq!(
        selection.tracks.len(),
        crate::selection::PLAYBACK_QUEUE_MAX_TRACKS
    );
    assert_eq!(selection.tracks.len(), 8);
    // Stable order ties on suitability and breaks by pack id ascending, so the
    // primary is item-0 and the queue fills pack-1..pack-7 in ranked order.
    assert_eq!(selection.primary().item_id, "item-0");
    let ids: Vec<_> = selection.tracks.iter().map(|t| t.item_id.clone()).collect();
    assert_eq!(
        ids,
        vec!["item-0", "item-1", "item-2", "item-3", "item-4", "item-5", "item-6", "item-7"]
    );
    let mut seen = BTreeSet::new();
    for track in &selection.tracks {
        assert!(
            seen.insert(track.item_id.clone()),
            "duplicate item in queue"
        );
    }
}

#[test]
fn loop_queue_skips_over_budget_candidate_and_keeps_smaller_followups() {
    let bytes = asset_bytes();
    let primary = single_loop_manifest(&bytes, "pack-primary", "item-primary", 10.0, 0.9);
    // 756s stereo 44.1kHz ~= 66.68M samples: fits the decoded budget alone but
    // not alongside the primary, so it must be skipped rather than terminating
    // the queue.
    let big = single_loop_manifest(&bytes, "pack-big", "item-big", 756.0, 0.8);
    let small = single_loop_manifest(&bytes, "pack-small", "item-small", 10.0, 0.7);

    let selection = crate::select_playback_plan(
        &[primary, big, small],
        crate::PlaybackSelectionInput {
            activity: Activity::DeepWork,
            genre_id: None,
            mood_id: None,
            previous_item_id: None,
            item_feedback: &Default::default(),
        },
    )
    .unwrap();
    let ids: Vec<_> = selection.tracks.iter().map(|t| t.item_id.clone()).collect();
    assert_eq!(ids, vec!["item-primary", "item-small"]);
    let total_samples: f64 = selection.tracks.iter().map(estimated_samples).sum();
    assert!(total_samples <= crate::selection::PLAYBACK_MAX_DECODED_SAMPLES);
}

#[test]
fn loop_queue_respects_cumulative_decoded_budget_below_max_tracks() {
    let bytes = asset_bytes();
    // 200s stereo 44.1kHz ~= 17.64M samples each; only three fit the 64M sample
    // budget even though eight distinct eligible tracks exist.
    let manifests: Vec<_> = (0..10)
        .map(|index| {
            single_loop_manifest(
                &bytes,
                &format!("pack-{index}"),
                &format!("item-{index}"),
                200.0,
                0.8,
            )
        })
        .collect();
    let selection = crate::select_playback_plan(
        &manifests,
        crate::PlaybackSelectionInput {
            activity: Activity::DeepWork,
            genre_id: None,
            mood_id: None,
            previous_item_id: None,
            item_feedback: &Default::default(),
        },
    )
    .unwrap();
    assert!(selection.tracks.len() <= crate::selection::PLAYBACK_QUEUE_MAX_TRACKS);
    assert_eq!(selection.tracks.len(), 3);
    let total_samples: f64 = selection.tracks.iter().map(estimated_samples).sum();
    assert!(total_samples <= crate::selection::PLAYBACK_MAX_DECODED_SAMPLES);
    let mut seen = BTreeSet::new();
    for track in &selection.tracks {
        assert!(
            seen.insert(track.item_id.clone()),
            "duplicate item in queue"
        );
    }
}

#[test]
fn loop_queue_applies_genre_filter_feedback_ranking_and_excludes_distracting() {
    let bytes = asset_bytes();
    let mut helpful = single_loop_manifest(&bytes, "pack-helpful", "item-helpful", 10.0, 0.7);
    helpful.items[0].genre_ids = vec!["test-atmospheric".to_owned()];
    let mut neutral = single_loop_manifest(&bytes, "pack-neutral", "item-neutral", 10.0, 0.9);
    neutral.items[0].genre_ids = vec!["test-atmospheric".to_owned()];
    let mut distracting =
        single_loop_manifest(&bytes, "pack-distracting", "item-distracting", 10.0, 1.0);
    distracting.items[0].genre_ids = vec!["test-atmospheric".to_owned()];
    let mut other_genre = single_loop_manifest(&bytes, "pack-other", "item-other", 10.0, 1.0);
    other_genre.items[0].genre_ids = vec!["test-rhythmic".to_owned()];

    let mut feedback = BTreeMap::new();
    feedback.insert("item-helpful".to_owned(), TrackFeedback::HelpsFocus);
    feedback.insert("item-distracting".to_owned(), TrackFeedback::Distracting);

    let selection = crate::select_playback_plan(
        &[helpful, neutral.clone(), distracting, other_genre],
        crate::PlaybackSelectionInput {
            activity: Activity::DeepWork,
            genre_id: Some("test-atmospheric"),
            mood_id: None,
            previous_item_id: None,
            item_feedback: &feedback,
        },
    )
    .unwrap();
    let ids: Vec<_> = selection.tracks.iter().map(|t| t.item_id.clone()).collect();
    // Helpful feedback outranks the higher-suitability neutral track; the
    // distracting and wrong-genre tracks never enter the queue.
    assert_eq!(ids, vec!["item-helpful", "item-neutral"]);
    assert!(selection
        .tracks
        .iter()
        .all(|t| t.genre_ids == ["test-atmospheric"]));

    // Without the helpful signal the distracting track is still excluded and the
    // genre filter still holds, leaving only the neutral track.
    let empty = BTreeMap::new();
    let only_neutral = crate::select_playback_plan(
        &[neutral],
        crate::PlaybackSelectionInput {
            activity: Activity::DeepWork,
            genre_id: Some("test-atmospheric"),
            mood_id: None,
            previous_item_id: None,
            item_feedback: &empty,
        },
    )
    .unwrap();
    assert_eq!(only_neutral.tracks.len(), 1);
    assert_eq!(only_neutral.primary().item_id, "item-neutral");
}

#[test]
fn loop_queue_single_track_is_a_valid_one_track_program() {
    let bytes = asset_bytes();
    let manifest = single_loop_manifest(&bytes, "pack-solo", "item-solo", 10.0, 0.8);
    let selection = crate::select_playback_plan(
        &[manifest],
        crate::PlaybackSelectionInput {
            activity: Activity::DeepWork,
            genre_id: None,
            mood_id: None,
            previous_item_id: None,
            item_feedback: &Default::default(),
        },
    )
    .unwrap();
    assert_eq!(selection.tracks.len(), 1);
    assert_eq!(selection.primary().item_id, "item-solo");
}

#[test]
fn loop_queue_rotates_primary_away_from_previous_item_without_dropping_it() {
    let bytes = asset_bytes();
    let manifests = vec![
        single_loop_manifest(&bytes, "pack-a", "item-a", 10.0, 0.9),
        single_loop_manifest(&bytes, "pack-b", "item-b", 10.0, 0.8),
        single_loop_manifest(&bytes, "pack-c", "item-c", 10.0, 0.7),
    ];
    let selection = crate::select_playback_plan(
        &manifests,
        crate::PlaybackSelectionInput {
            activity: Activity::DeepWork,
            genre_id: None,
            mood_id: None,
            previous_item_id: Some("item-a"),
            item_feedback: &Default::default(),
        },
    )
    .unwrap();
    assert_eq!(selection.primary().item_id, "item-b");
    let ids: Vec<_> = selection.tracks.iter().map(|t| t.item_id.clone()).collect();
    assert_eq!(ids, vec!["item-b", "item-a", "item-c"]);
}
